---
- name: Check if docker-gen is installed
  stat: path=/usr/local/bin/docker-gen
  register: docker_gen_bin_file

- include: docker-gen-install.yml
  when: docker_gen_bin_file.stat.exists == False
