---
- name: Ensure /etc/h2o directory exists
  file: path=/etc/h2o state=directory mode=0700

- name: Check if h2o.conf exists
  stat: path=/etc/h2o/h2o.conf
  register: h2o_conf_file

- name: Create h2o.conf if not present yet
  shell: docker-gen /etc/docker-gen/templates/h2o.tmpl /etc/h2o/h2o.conf
  when: h2o_conf_file.stat.exists == False

- name: Ensure /etc/h2o/ssl directory exists
  file: path=/etc/h2o/ssl state=directory mode=0700

- stat: path=/etc/h2o/ssl/self-signed.crt
  register: h2o_self_signed_cert_file

- name: Create a self-signed SSL cert
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /etc/h2o/ssl/self-signed.key -out /etc/h2o/ssl/self-signed.crt \
          -subj "/C=US/ST=NY/L=NYC/O=IT/CN={{ h2o_self_signed_certificate_cn }}"
  when: h2o_self_signed_cert_file.stat.exists == False

- name: Create www directory
  file: path=/srv/www state=directory mode=0755 owner=root

- name: Create default www directory
  file: path=/srv/www/default state=directory mode=0755

- name: Copy index.html file
  copy: src=index.html dest=/srv/www/default/index.html

- name: Ensure we have a h2o container running
  docker_container:
    name: h2o
    state: started
    image: "{{ h2o_image }}"
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - /etc/h2o:/etc/h2o:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/www:/srv/www:ro
    command:
      - h2o
      - -m
      - master
