---
- name: Create letsencrypt user
  user: name=letsencrypt state=present system=yes uid=1250 createhome=no

- name: Create /etc/letsencrypt directory
  file: path=/etc/letsencrypt state=directory mode=0700 owner=letsencrypt

- name: Copy cli.ini
  template: src=cli.ini dest=/etc/letsencrypt/cli.ini owner=letsencrypt

- stat: path=/etc/letsencrypt/domains.conf
  register: letsencrypt_domains_conf_file

- name: Touch domains.conf if absent
  file: path=/etc/letsencrypt/domains.conf state=touch mode=600 owner=letsencrypt
  when: letsencrypt_domains_conf_file.stat.exists == False

- name: Check if dhparam file exists
  stat: path=/etc/letsencrypt/dhparam.pem
  register: dhparam_file

- name: Generate dhparam file (could take a while...)
  shell: openssl dhparam -out /etc/letsencrypt/dhparam.pem 2048 && chmod 400 /etc/letsencrypt/dhparam.pem
  when: dhparam_file.stat.exists == False

- name: Create letsencrypt webroot directory
  file: path=/srv/www/letsencrypt state=directory mode=0755 owner=letsencrypt

- name: Create letsencrypt var/lib directory
  file: path=/var/lib/letsencrypt state=directory mode=700 owner=letsencrypt

- name: Copy update script
  copy: src=scripts/letsencrypt-docker-gen-update.sh dest=/usr/local/bin/letsencrypt-docker-gen-update.sh mode=700

- name: Ensure letsencrypt log directory exists
  file: path=/var/log/letsencrypt state=directory mode=700

- stat: path=/var/log/letsencrypt/docker-gen-update.log
  register: letsencrypt_log_file

- name: Ensure log file exists
  file: path=/var/log/letsencrypt/docker-gen-update.log state=touch mode=600
  when: letsencrypt_log_file.stat.exists == False

- name: Ensure we have a Let's encrypt container ready
  docker_container:
    name: letsencrypt-docker-gen-updater
    state: present
    image: "{{ letsencrypt_image }}"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /srv/www/letsencrypt:/srv/www/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
